### ISSUE TITLE
No data from Realtek Bluetooth 5.1 Radio

### ISSUE THREAD

**Issue by AriZuu** [google/bumble#100]
I got a bluetooth dongle with Realtek chip because it has external antenna. But for some reason or another, it doesn't appear to receive anything.

Probe finds it ok:
``` 
(vble) % bumble-usb-probe
ID 0BDA:8771
  Bumble Transport Names: usb:0 or usb:0BDA:8771 or usb:0BDA:8771/00E04C239987
  Bus/Device:             000/002
  Class:                  Wireless Controller
  Subclass/Protocol:      1/1 [Bluetooth]
  Serial:                 00E04C239987
  Manufacturer:           Realtek
  Product:                Bluetooth 5.1 Radio
```

But when starting scan, nothing is displayed.
```
(vble) % bumble-scan usb:0
<<< connecting to HCI...
<<< connected
```

I have an other dongle with Broadcom chipset at same room, it works ok with bumble - running scan prints a lot of advertisements. Is the Realtek chip just not supported ? Or is the dongle broken ?

(I'll have to say that this is great stuff. I'm using bumble to connect nrf52 based environment sensors I have developed. So much easier than c-language approach I had previously)

**Comment by barbibulle** [comment]
All the Realtek dongles I’ve encountered so far have the same issue: while they do expose a standard HCI USB interface, they require a firmware image to be loaded at init time before they become fully functional. There are a number of such binaries that can be obtained from Realtek. What’s missing still is the bit of code that will load the binary into the dongle using vendor-specific HCI commands. The Linux Bluetooth subsystem has support for that, so it isn’t super difficult to figure out how to do it, but I haven’t had the time to implement that yet. I was planning on investigating that over the coming weeks. I’ll post some PRs and would love some testers if you’re interested.

**Comment by AriZuu** [comment]
If the firmware image could be loaded via python that would be great. I'm working on FreeBSD, so this would be super interesting. I'm willing to test PRs related to this, it's no problem as I already have bumble repository clone on server with Realtek dongle. Looking forward to this.

**Comment by uael** [comment]
The linux version of the fm update is located here: https://github.com/torvalds/linux/blob/master/drivers/bluetooth/btrtl.c
Binaries are located in `/sys/module/firmware_class/parameters/path/rtl_bt/rtl${VERSION}_{fw,config}.bin`

**Comment by barbibulle** [comment]
In theory, manually loading the FW with the rtk util tool shouldn’t be necessary, it should be automatically detected and loaded. If that’s not the case, please let me know (test after unplugging the dongle and re-plugging, since loading FW is persistent across resets).

**Comment by AriZuu** [comment]
That depends on operating system, I guess. I'm FreeBSD user and it doesn't have native support for that Realtek dongle. But it works great with bumble (FW loading can be automated so that system calls rtk util when device is plugged in).

**Comment by barbibulle** [comment]
What I meant is that when the Bumble Host object is created (typically when instantiating a Device object), with a usb transport, the library will look if the usb dongle is in the list ok known product_if/vendor_id, and it it is, locate the appropriate FW and config files and load them, assuming that they have been downloaded and reside on the FW search path (same result as manually calling “load” with the rtk util tool). If your product_id/vendor_id isn’t in the list, we should add it, so that others can benefit from this auto-loading as well.

**Comment by AriZuu** [comment]
I didn't understand that this was so sophisticated. Indeed, I can confirm that manually calling "load" is not necessary. Great stuff!
