### ISSUE TITLE
Remove dependency on GPL-3 library

### ISSUE THREAD

**Issue by akuker** [google/bumble#123]
One of the dependencies for Bumble is `aioconsole`. This is distributed under GPL v3, which is an extremely aggressive copy-left license. Depending upon your interpretation of GPL v3, this might not be compatible with the project's Apache 2.0 license.

The Bumble project may want to consider migrating away from this dependency in order to maintain the current project license.

According to PyPi:

> The python console exposed by [aioconsole](https://pypi.python.org/pypi/aioconsole) is quite limited compared to modern consoles such as [IPython](https://ipython.readthedocs.io/) or [ptpython](https://github.com/prompt-toolkit/ptpython). Luckily, those projects gained greater asyncio support over the years. In particular, the following use cases overlap with [aioconsole](https://pypi.python.org/pypi/aioconsole) capabilities:
> 
> [Embedding a ptpython console in an asyncio program](https://github.com/prompt-toolkit/ptpython/blob/master/examples/asyncio-python-embed.py)
> 
> [Using the await syntax in an IPython console](https://ipython.readthedocs.io/en/stable/whatsnew/version7.html#autowait-asynchronous-repl)

The other dependencies appear compatible with the Apache 2.0 license. (But, I am not a lawyer....)

**Comment by barbibulle** [comment]
Thanks for the suggestion. That makes sense. `aioconsole` is only used for a very simple, limited purpose, and will be easy to replace (just needed to read the response to a prompt in a terminal, nothing fancy). I'll have a PR shortly.

**Comment by barbibulle** [comment]
`aioconsole` has been replaced as of the latest commit.
