### ISSUE TITLE
vhci Adapter not visible to chromium on Raspberry Pi

### ISSUE THREAD

**Issue by michael-barrow** [google/bumble#127]
I have been trying to access the example characteristics from the example device in  the `run_controller.py` example. I have followed the vhci steps here (https://google.github.io/bumble/platforms/linux.html#using-vhci).

Although I can see the virtual controller in hciconfig, as well as connect to the virtual device attached to it using `bluetoothctl` and then list characteristics, I cannot do the same in chromium because chromium cannot see the bumble vhci adapter.

I have tried disabling the pi's built in adapter and re-starting chrome, but still it is not aware of the bumble vhci adapter.

I am not sure if this is a limitation of bumble or chrome, but I was hoping to use bumble to develop a heart rate monitoring application as a replacement for my physical device which works well with chrome when connected via the pi's real controller.

### Steps to Reproduce

In terminal window A, start the bumble example:

```
cd $BUMBLE_ROOT
sudo chmod 766 /dev/vhci
python3 examples/run_controller.py F6:F7:F8:F9:FA:FB examples/device1.json vhci
```

In terminal window B, disable other adapter(s) , verify virtual characteristics

```
sudo hciconfig hci0 down
bluetoothctl
menu scan
transport le
back
scan on
pair F0:F1:F2:F3:F4:F5
trust F0:F1:F2:F3:F4:F5
scan off
```
![virtualdeviceservices](https://user-images.githubusercontent.com/20428997/217997915-f8d784c0-edf3-4081-9f8c-492531ed7240.png)

Open a chromium window, verify bluetooth is enabled and verify that the bumble adapter (C7:C4:87:86:93:12) is not detected. In the search bar:

(enable bluetooth) chrome://flags/#enable-experimental-web-platform-features
(check detected adapter) chome://bluetooth-internals/

![chromiumbluetooth](https://user-images.githubusercontent.com/20428997/217998553-0bf9afe9-04e1-40e2-b3a1-895166f35a48.png)

The virtual controller is not detected, so chrome is unable to read services from the virtual Bumble device provided by `run_controller.py` since scanning for it will always fail

**Comment by barbibulle** [comment]
I ran a simple experiment on a Ubuntu laptop (not an rpi but close enough for this test). What I see is that Chromium only uses hci0. Even if you have a single adapter and it isn’t hci0 (for example you start with two, so you get hci0 and hci1, then remove hci0, you’re left with just hci1), it won’t use it.
With the virtual adapter visible as hci0, I am able to “see” it from Chromium, no problem (Using the builtin bluetooth-internals page, I can scan, connect and inspect the simple GATT server from the run_controller example app).
(a quick look at the Chromium source code seems to confirm that. https://chromium.googlesource.com/chromium/src/+/refs/heads/main/device/bluetooth/bluez/bluetooth_adapter_bluez.cc#376 —> `SetAdapter(object_paths[0])` )

**Comment by michael-barrow** [comment]
Thanks! 

Glad to know what is going on, I will follow up on the Chromium repository to see if this is a bug (multiple controllers are supported on other platforms) or a limitation.

Cheers again.
