### ISSUE TITLE
[Feature Request] Delegate SMP address information

### ISSUE THREAD

**Issue by zxzxwu** [google/bumble#165]
Currently, SMP always sends the address type corresponding to its connection
https://github.com/google/bumble/blob/044597de66355672a5bba42fda455fe9c653337d/bumble/smp.py#L1038

However, in some cases(especially on Dual-mode devices), users may want to perform RPA exchange over a connection using random address(or vice versa, though it makes no sense).

**Comment by barbibulle** [comment]
This feature should now be supported with PR #231  , right?

**Comment by zxzxwu** [comment]
Yes for the SMP part. Another issue is that bumble doesn't support address resolution yet. There is only a `random_address` field in device probably hold all kind of address here.
