### ISSUE TITLE
Notifier - usecase on windows

### ISSUE THREAD

**Issue by pymenow** [google/bumble#179]
I am trying the sample notifier with the below command. My use case is to emulate a BT device that is discoverable and can be connected to from either an iOS or Android phone / app.

python ./run_notifier.py test.json usb:0

{
    "name": "Test-sim",
    "address": "F6:F7:F8:F9:FA:FB",
    "keystore": "JsonKeyStore",
    "irk": "43E96EC5C5DBD8D0F5204CFFDECE0096",
    "advertising_interval": 100,
    "advertising_data": "0201061106ba5689a6fabfa2bd01467d6e00fbabad08160a181604659b03"
}

This seem to go through fine. last few debug prints as below. But when I search for the device from my phone it doesnt find it. Trying to understand what I amy be doing wrong.

DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND:
  advertising_interval_min:  2000
  advertising_interval_max:  2000
  advertising_type:          ADV_IND
  own_address_type:          RANDOM
  peer_address_type:         PUBLIC_DEVICE_ADDRESS
  peer_address:              00:00:00:00:00:00
  advertising_channel_map:   7
  advertising_filter_policy: 0
DEBUG:bumble.transport.usb:submit COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_ADVERTISING_ENABLE_COMMAND:
  advertising_enable: 1
DEBUG:bumble.transport.usb:submit COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_ADVERTISING_ENABLE_COMMAND
  return_parameters:       HCI_SUCCESS

**Comment by pymenow** [comment]
On Linux I was able to discover bumble , but only on my laptop where I had it running using the primary Bluetooth controller.
Am i missing on how this works ?

**Comment by pymenow** [comment]
OK got this working where I can in Windows run the ./run_notifier.py but had to change the characteristic UUID. Now I can connect from my Android phone, but cant see this on iOS yet. Thanks !

**Comment by barbibulle** [comment]
Which application are you using on the phone to discover the advertising device? If you use the builtin BT prefs/settings and try « add new device » that will filter things and only show you devices that advertise services that the phone understands. So if you only advertise a custom service, it might not show up. You should first try with a generic scanner app, like nRF Connect for example (available both on iOS and Android)

**Comment by pymenow** [comment]
Thanks for the response. I was able to resolve the issues.

1. Started using run_notifier.py & updated the custom services , the json had to be derived from device1.json 
2. The Device name wouldnt show up on most scans, had to include device.advertising_data as in heart_rate_service.py.
3. Once the above was done , I have mosly resolved my issues.

From a contribution perspective Ive created class TimeService(TemplateService) , similar to battery service and it works as per the BT spec , i could check that in.

And yes to debug the issues I did use nRF connect ! Thanks again appriciate you taking time to respond. 

time_service.py

`import datetime
from bumble.gatt_client import ProfileServiceProxy
from bumble.gatt import (
    GATT_CURRENT_TIME_SERVICE,
    GATT_CURRENT_TIME_CHARACTERISTIC,
    TemplateService,
    Characteristic,
    CharacteristicValue,
    PackedCharacteristicAdapter,
)

# -----------------------------------------------------------------------------
class TimeService(TemplateService):
    UUID = GATT_CURRENT_TIME_SERVICE
    CURRENT_TIME_FORMAT = 'HBBBBBBBB'

    def __init__(self, read_current_time):
        self.current_time_characteristic = PackedCharacteristicAdapter(
            Characteristic(
                GATT_CURRENT_TIME_CHARACTERISTIC,
                Characteristic.READ | Characteristic.WRITE_WITHOUT_RESPONSE,
                Characteristic.READABLE,
                CharacteristicValue(read=read_current_time),
            ),
            pack_format=TimeService.CURRENT_TIME_FORMAT,
        )
        super().__init__([self.current_time_characteristic])

    @staticmethod
    def get_current_time_bytes(self):
        now = datetime.datetime.now()
        year = now.year
        month = now.month
        day = now.day
        hours = now.hour
        minutes = now.minute
        seconds = now.second
        day_of_week = now.isoweekday()
        fractions = (now.microsecond // 256 % 256)
        adjust_reason = 0

        return year, month, day, hours, minutes, seconds, day_of_week, fractions, adjust_reason


# -----------------------------------------------------------------------------
class TimeServiceProxy(ProfileServiceProxy):
    SERVICE_CLASS = TimeService

    def __init__(self, service_proxy):
        self.service_proxy = service_proxy

        if characteristics := service_proxy.get_characteristics_by_uuid(
            GATT_CURRENT_TIME_CHARACTERISTIC
        ):
            self.current_time = PackedCharacteristicAdapter(
                characteristics[0], pack_format=TimeService.CURRENT_TIME_FORMAT
            )
        else:
            self.current_time = None
`

**Comment by barbibulle** [comment]
I'm glad that it worked out.
