### ISSUE TITLE
Windows : Either during unbond or updating the keys , get FileExistsError

### ISSUE THREAD

**Issue by pymenow** [google/bumble#181]
exception=FileExistsError(17, 'Cannot create a file when that file already exists')>
Traceback (most recent call last):

    await keystore.delete(address)
  File "\Python39\site-packages\bumble\keys.py", line 270, in delete
    await self.save(db)
  File "\Python39\site-packages\bumble\keys.py", line 260, in save
    os.rename(temp_filename, self.filename)
FileExistsError: [WinError 183] Cannot create a file when that file already exists: 

The error occurs when the bumble.keys tries to rename the temporary file to the original file, but the original file already exists. On Windows, the os.rename function will raise a FileExistsError if the destination file already exists. To fix this issue, you can use the shutil.move function, which will overwrite the destination file if it exists. 

import shutil
shutil.move(temp_filename, self.filename)

**Comment by pymenow** [comment]
Added a patch file.
[0001-Fix-for-181-Fix-file-exists-error-on-windows-during-.patch](https://github.com/google/bumble/files/11359308/0001-Fix-for-181-Fix-file-exists-error-on-windows-during-.patch)

**Comment by barbibulle** [comment]
Thanks for reporting this. Should be fixed in PR #183 (using `os.replace` instead of `shutil.move`, should achieve the same result).

**Comment by uael** [comment]
Fixed in #183
