### ISSUE TITLE
Bumble stops working on Android when having (too?) many characteristics

### ISSUE THREAD

**Issue by eliaslecomte** [google/bumble#202]
Hi,

We are using this great project with a Nordic nRF52840 dongle.
However we notice that when having many characteristics, it stops working for (some) Android devices.

I have added about 170 (notifiable) characteristics and while I initially have no errors when starting the python code, bonding is never triggered and bluetooth connection times out.

Any idea what is going on, and if I could solve this?

**Comment by barbibulle** [comment]
Hi. I which direction is the connection? (Phone to dongle or dongle to phone?). Do you observe a disconnection after the timeout, or are things just stuck?
If you can post a log of the HCI packet exchange (setting BUMBLE_LOGLEVEL=DEBUG) that may tell us what’s going on.

**Comment by eliaslecomte** [comment]
Hi there, thanks for the quick reply and help offered!

The smartphone connects to the nrf stick. The services and characteristics simulate an IoT device.

This is my log:

`Descriptor(handle=0x0217, type=UUID-16:2902 (Client Characteristic Configuration), value=)
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_RESET_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_RESET_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_READ_LOCAL_SUPPORTED_COMMANDS_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_READ_LOCAL_SUPPORTED_COMMANDS_COMMAND
  return_parameters:       
    status:             HCI_SUCCESS
    supported_commands: 2000800000c000000000e40000002822000000000000040000f7ffff7f00000030f0f9ff0100801c000000000001000000000000000000000000000000000000
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_READ_LOCAL_SUPPORTED_FEATURES_COMMAND
  return_parameters:       
    status:      HCI_SUCCESS
    le_features: ff49010000000000
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND
  return_parameters:       
    status:             HCI_SUCCESS
    hci_version:        12
    hci_subversion:     0
    lmp_version:        12
    company_identifier: 1521
    lmp_subversion:     65535
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_SET_EVENT_MASK_COMMAND:
  event_mask: ffffffffffffff3f
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_SET_EVENT_MASK_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_EVENT_MASK_COMMAND:
  le_event_mask: fffff00000000000
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_EVENT_MASK_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_READ_BUFFER_SIZE_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_READ_BUFFER_SIZE_COMMAND
  return_parameters:       
    status:                           HCI_SUCCESS
    hc_le_acl_data_packet_length:     27
    hc_total_num_le_acl_data_packets: 7
DEBUG:bumble.host:HCI LE ACL flow control: hc_le_acl_data_packet_length=27,hc_total_num_le_acl_data_packets=7
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_READ_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND
  return_parameters:       
    status:                  HCI_SUCCESS
    suggested_max_tx_octets: 27
    suggested_max_tx_time:   328
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND:
  suggested_max_tx_octets: 251
  suggested_max_tx_time:   2120
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_WRITE_SUGGESTED_DEFAULT_DATA_LENGTH_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_READ_BD_ADDR_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_READ_BD_ADDR_COMMAND
  return_parameters:       
    status:  HCI_SUCCESS
    bd_addr: 00:00:00:00:00:00/P
DEBUG:bumble.device:BD_ADDR: 00:00:00:00:00:00/P
DEBUG:bumble.device:LE Random Address: F1:F2:F2:F3:F5:F9
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_RANDOM_ADDRESS_COMMAND:
  random_address: F1:F2:F2:F3:F5:F9
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_RANDOM_ADDRESS_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_CLEAR_RESOLVING_LIST_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_CLEAR_RESOLVING_LIST_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_ADD_DEVICE_TO_RESOLVING_LIST_COMMAND:
  peer_identity_address_type: PUBLIC_DEVICE_ADDRESS
  peer_identity_address:      24:11:53:39:00:5A/P
  peer_irk:                   47b237d420493f3debdf6ac5091dbc74
  local_irk:                  f9f5f3f2f2f1f9f5f3f2f2f1f9f5f3f2
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_ADD_DEVICE_TO_RESOLVING_LIST_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_ADVERTISING_DATA_COMMAND:
  advertising_data: 0c09425243314b20456c6961731106000024b201883aad2c435cbc1965e03c
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_ADVERTISING_DATA_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND:
  scan_response_data: 
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_SCAN_RESPONSE_DATA_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND:
  advertising_interval_min:  100
  advertising_interval_max:  100
  advertising_type:          ADV_IND
  own_address_type:          RANDOM
  peer_address_type:         PUBLIC_DEVICE_ADDRESS
  peer_address:              00:00:00:00:00:00
  advertising_channel_map:   7
  advertising_filter_policy: 0
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_ADVERTISING_PARAMETERS_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_LE_SET_ADVERTISING_ENABLE_COMMAND:
  advertising_enable: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_LE_SET_ADVERTISING_ENABLE_COMMAND
  return_parameters:       HCI_SUCCESS
`

**Comment by barbibulle** [comment]
The first log, with Android, shows that the virtual device with the Nordic dongle is advertising, waiting for a connection. But there is no connection from the phone at all.
On the phone side, can you tell if the phone even finds the device an attempts to connect to it, or does it timeout looking for the device's advertisements?

**Comment by eliaslecomte** [comment]
So far this is what I have figured out.

* if the nrf starts with a new mac, and I load this many characteristics
* app can connect with nrf 5
* times out upon discovering all services and characterstics after about 35 seconds, this does happen on most (even recent) android devices but not all

The log while disvering is very long, here are the last few entries:

```
DEBUG:bumble.gatt_server:GATT Response from server: [0x0000] ATT_FIND_INFORMATION_RESPONSE:
  format:      1
  information: 0x020E:0229
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0000pb=0, bc=0, data_total_length=10, data=0600040005010e020229
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0000pb=2, bc=0, data_total_length=9, data=050004000411021102
DEBUG:bumble.hci:<<< ACL PDU: 050004000411021102
DEBUG:bumble.gatt_server:GATT Request to server: [0x0000] ATT_FIND_INFORMATION_REQUEST:
  starting_handle: 0x0211
  ending_handle:   0x0211
DEBUG:bumble.gatt_server:GATT Response from server: [0x0000] ATT_FIND_INFORMATION_RESPONSE:
  format:      1
  information: 0x0211:0229
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0000pb=0, bc=0, data_total_length=10, data=06000400050111020229
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0000pb=2, bc=0, data_total_length=11, data=0700040008140217020228
DEBUG:bumble.hci:<<< ACL PDU: 0700040008140217020228
DEBUG:bumble.gatt_server:GATT Request to server: [0x0000] ATT_READ_BY_TYPE_REQUEST:
  starting_handle: 0x0214
  ending_handle:   0x0217
  attribute_type:  UUID-16:2802 (Include)
DEBUG:root:not found ATT_READ_BY_TYPE_REQUEST:
  starting_handle: 0x0214
  ending_handle:   0x0217
  attribute_type:  UUID-16:2802 (Include)
DEBUG:bumble.gatt_server:GATT Response from server: [0x0000] ATT_ERROR_RESPONSE:
  request_opcode_in_error:   ATT_READ_BY_TYPE_REQUEST
  attribute_handle_in_error: 0x0214
  error_code:                ATT_ATTRIBUTE_NOT_FOUND_ERROR
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0000pb=0, bc=0, data_total_length=9, data=05000400010814020a
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0000pb=2, bc=0, data_total_length=11, data=0700040008140217020328
DEBUG:bumble.hci:<<< ACL PDU: 0700040008140217020328
DEBUG:bumble.gatt_server:GATT Request to server: [0x0000] ATT_READ_BY_TYPE_REQUEST:
  starting_handle: 0x0214
  ending_handle:   0x0217
  attribute_type:  UUID-16:2803 (Characteristic)
DEBUG:bumble.gatt_server:GATT Response from server: [0x0000] ATT_READ_BY_TYPE_RESPONSE:
  length:     7
  attributes: 0x0215:201602052a
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0000pb=0, bc=0, data_total_length=13, data=0900040009071502201602052a
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0000pb=2, bc=0, data_total_length=11, data=0700040008160217020328
DEBUG:bumble.hci:<<< ACL PDU: 0700040008160217020328
DEBUG:bumble.gatt_server:GATT Request to server: [0x0000] ATT_READ_BY_TYPE_REQUEST:
  starting_handle: 0x0216
  ending_handle:   0x0217
  attribute_type:  UUID-16:2803 (Characteristic)
DEBUG:root:not found ATT_READ_BY_TYPE_REQUEST:
  starting_handle: 0x0216
  ending_handle:   0x0217
  attribute_type:  UUID-16:2803 (Characteristic)
DEBUG:bumble.gatt_server:GATT Response from server: [0x0000] ATT_ERROR_RESPONSE:
  request_opcode_in_error:   ATT_READ_BY_TYPE_REQUEST
  attribute_handle_in_error: 0x0216
  error_code:                ATT_ATTRIBUTE_NOT_FOUND_ERROR
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0000pb=0, bc=0, data_total_length=9, data=05000400010816020a
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0000pb=2, bc=0, data_total_length=9, data=050004000417021702
DEBUG:bumble.hci:<<< ACL PDU: 050004000417021702
DEBUG:bumble.gatt_server:GATT Request to server: [0x0000] ATT_FIND_INFORMATION_REQUEST:
  starting_handle: 0x0217
  ending_handle:   0x0217
DEBUG:bumble.gatt_server:GATT Response from server: [0x0000] ATT_FIND_INFORMATION_RESPONSE:
  format:      1
  information: 0x0217:0229
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0000pb=0, bc=0, data_total_length=10, data=06000400050117020229
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
```

What could I do to debug this better?

I am using https://github.com/dotintent/react-native-ble-plx.

**Comment by barbibulle** [comment]
I will try to replicate this on a few Android phones to see if I can make it fail in the same way. Regarding the case described earlier where the phone would not even connect, does that happen after a connection where it fails to fully discover all characteristics? Or is that a different issue?

**Comment by eliaslecomte** [comment]
I just started to notice I have a few of these logs at the very end of the discover services:

```
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:         1
  connection_handle[0]:     0
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0000pb=2, bc=0, data_total_length=11, data=07000400080b0213020228
DEBUG:bumble.hci:<<< ACL PDU: 07000400080b0213020228
DEBUG:bumble.gatt_server:GATT Request to server: [0x0000] ATT_READ_BY_TYPE_REQUEST:
  starting_handle: 0x020B
  ending_handle:   0x0213
  attribute_type:  UUID-16:2802 (Include)
DEBUG:root:not found ATT_READ_BY_TYPE_REQUEST:
  starting_handle: 0x020B
  ending_handle:   0x0213
  attribute_type:  UUID-16:2802 (Include)
DEBUG:bumble.gatt_server:GATT Response from server: [0x0000] ATT_ERROR_RESPONSE:
  request_opcode_in_error:   ATT_READ_BY_TYPE_REQUEST
  attribute_handle_in_error: 0x020B
  error_code:                ATT_ATTRIBUTE_NOT_FOUND_ERROR
--- Logging error ---
DEBUG:bumble.host:### HOST -> CONTROLLER: (CID=4) ACL: handle=0x0000pb=0, bc=0, data_total_length=9, data=0500040001080b020a
--- Logging error ---
```

**Comment by barbibulle** [comment]
I have tried with a Pixel 3a running Android 12, and a simple GATT server with 256 readable/writeable/notifiable characteristics (in one service), and that seems to work fine. I'll try to find other Android phones to test with.

**Comment by barbibulle** [comment]
Update: I'm able to reproduce the issue with a Pixel 6. I can now investigate what's going on. It might take a couple weeks before I can get to it, but I will follow up. Also, I checked with a different BT controller, I can reproduce the same issue, so it doesn't seem related to the specifics of the nrf52840 USB dongle.

**Comment by barbibulle** [comment]
The Android Bluetooth stack has a compiled-in limit for the maximum number of characteristic registrations (see https://cs.android.com/android/platform/superproject/main/+/main:packages/modules/Bluetooth/system/bta/gatt/bta_gattc_int.h;l=238;bpv=1;bpt=1 ). It used to be 15 a while back, more recent versions have it at 64, and some phone manufacturers may have they own customization. I don't think there's an way way to check from your app code what that limit is, unfortunately.
