### ISSUE TITLE
GATT Properties test failures and mypy errors in Python 3.11

### ISSUE THREAD

**Issue by zxzxwu** [google/bumble#224]
In Python 3.11, tests fail on cases:

```
tests/gatt_test.py::test_char_property_to_string FAILED                                   [ 60%]
tests/gatt_test.py::test_server_string FAILED                                             [ 75%]
```

and mypy generates errors:
```
bumble/gatt.py:323: error: Incompatible return value type (got "object", expected "Properties")  [return-value]
```

This is probably because [change in Python 3.11](https://docs.python.org/3/library/enum.html#enum.IntEnum)

> Changed in version 3.11: [__str__()](https://docs.python.org/3/reference/datamodel.html#object.__str__) is now int.__str__() to better support the replacement of existing constants use-case. [__format__()](https://docs.python.org/3/reference/datamodel.html#object.__format__) was already int.__format__() for that same reason.

**Comment by zxzxwu** [comment]
I am wondering if this kind of comparison is neccessary? @AlanRosenthal 

Even explicitly implement `__str__()` as `f'Properties.{self.name}'`, it still don't give the correct order, which makes tests flaky.

**Comment by barbibulle** [comment]
PR #227 should fix this.

**Comment by zxzxwu** [comment]
Verified
