### ISSUE TITLE
Loading in Pyodide fails due to missing `cryptography` package

### ISSUE THREAD

**Issue by mauricelam** [google/bumble#284]
We are loading bumble in Pyodide in a browser, and running into an issue where it says the `cryptography` package is not installed.

The installation code for bumble looks like this"

```ts
await pyodide.loadPackage('micropip');
await pyodide.runPythonAsync('import micropip; await micropip.install("bumble")')
```

And the error message is

```
PythonError: Traceback (most recent call last):
  File "/lib/python311.zip/_pyodide/_base.py", line 540, in eval_code_async
    await CodeRunner(
  File "/lib/python311.zip/_pyodide/_base.py", line 363, in run_async
    coroutine = eval(self.code, globals, locals)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<exec>", line 22, in <module>
  File "/lib/python3.11/site-packages/bumble/device.py", line 158, in <module>
    from .pairing import PairingConfig
  File "/lib/python3.11/site-packages/bumble/pairing.py", line 28, in <module>
    from .smp import (
  File "/lib/python3.11/site-packages/bumble/smp.py", line 59, in <module>
    from . import crypto
  File "/lib/python3.11/site-packages/bumble/crypto.py", line 28, in <module>
    from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
ModuleNotFoundError: The module 'cryptography' is included in the Pyodide distribution, but it is not installed.
You can install it by calling:
  await micropip.install("cryptography") in Python, or
  await pyodide.loadPackage("cryptography") in JavaScript
See https://pyodide.org/en/stable/usage/loading-packages.html for more details.
```

I can easily add the `micropip.install("cryptography")` call, but I am wondering if `setup.cfg` can be updated to avoid the issue in the first place?

https://github.com/google/bumble/blob/5af347b499b26c2d0431f2a00a3c4f44290e6ec2/setup.cfg#L38

Thank you for your time!

**Comment by barbibulle** [comment]
You're 100% right. `cryptography` should be installed as a dependency via setup.cfg. This fell through the cracks as I forgot the examples included an explicit install of the package that was put there during development. I'll push a PR shortly to fix that.

**Comment by barbibulle** [comment]
Sorry for the snafu. I had to revert the merged PR. Now I remember why `cryptography` was installed "manually" and not via a `setup.cfg` dependency: there's no pure-python wheel for that package, so pyiodide refuses to load it that way. But installing it via `micropip.install` will find the built-in one.
Maybe there's a way to get pyiodide to do the right thing even when pulled in as a package dependency, but until/unless we find that alternative, we'll stick with the current appoach.

**Comment by barbibulle** [comment]
For reference, the error thrown by pyiodide is:
```
ValueError: Can't find a pure Python 3 wheel for 'cryptography==39'.
See: https://pyodide.org/en/stable/usage/faq.html#micropip-can-t-find-a-pure-python-wheel
```
