### ISSUE TITLE
 virtual printer

### ISSUE THREAD

**Issue by Eonassis** [google/bumble#346]
I'm new here, I need to simulate a bluetooth device on Android, it should work as a virtual printer, and what is sent to it should be in a file, can someone give me a way. everything must happen inside a real android device

**Comment by zxzxwu** [comment]
What protocol is your scenario going to use?

**Comment by barbibulle** [comment]
@Eonassis If you want to run a virtual Bluetooth device purely on Android, Bumble may not be a good solution for you, since it is written in Python. While it's technically possible to run some python code inside an Android app, that's highly complex and quite inefficient. Or did I misundertand your use case?

**Comment by Eonassis** [comment]
> What protocol is your scenario going to use?

simulate  BLE Printer

**Comment by Eonassis** [comment]
> @Eonassis If you want to run a virtual Bluetooth device purely on Android, Bumble may not be a good solution for you, since it is written in Python. While it's technically possible to run some python code inside an Android app, that's highly complex and quite inefficient. Or did I misundertand your use case?

I understand this question, but I need to simulate a BLE bluetooth printer, could you help me how would I do this??

**Comment by Eonassis** [comment]
> > > What protocol is your scenario going to use?
> > 
> > 
> > simulate BLE Printer
> 
> AFAIK there is only a [Basic Printing Profile](https://www.bluetooth.com/specifications/specs/basic-printing-profile-1-0/) which is not very common and Android doesn't support it. Most printers use their customized apps to interact with printers (usually via GATT), so if you want to simulate a printer, you need to get the spec of protocol you are going to simulate, and then implement the GATT server using Bumble.
> 
> You may begin with [examples/run_gatt_server.py ](https://github.com/google/bumble/blob/main/examples/run_gatt_server.py)and use some apps like [nRF connect](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp&pcampaignid=web_share) to understand how GATT works.


Thanks in advance for your help, I can run run_gatt_server.py within Android, as it is a real device with Android 7.1, I also checked that there is [https://github.com/google/bumble/tree/main/extras/android/RemoteHCI] , does this app solve my problem?

**Comment by zxzxwu** [comment]
First, I cannot understand what's your problem. We don't know what's the spec of the "printer", and we don't even know you want to "simulate Android as a printer" or "simulate a printer and make it connect to Android". If you want to do the previous one, then you can use RemoteHCI. For the other one, getting a Bluetooth dongle will be much easier.

**Comment by zxzxwu** [comment]
And even if you want to simulate "on Android", it would be much easier to achieve this by writing an Android GATT server app with Android SDK.

**Comment by Eonassis** [comment]
> And even if you want to simulate "on Android", it would be much easier to achieve this by writing an Android GATT server app with Android SDK. 

The GATT server only simulates a BLE device for another cell phone, in this case I need two devices with Bluetooth to work. However, I would like to do everything on the same device.

I need to simulate a bluetoothLE virtual device on Android, the android must connect to it and exchange information, and what is sent to the ble device must be saved in a file inside the android, everything must happen inside a real Android device simulating a bluetoothLE virtual device.

I have apk's that only send prints via a bluetoothLE device, however we will no longer use printers, in the app there is no option to save as a PDF or send it to the Android printer.

I don't have access to the application source to make changes directly to the source code.

Faced with the problem, my idea would be to create a virtual BLE device where the android could virtually connect to it and send the data that would be saved in a file. This is my problem.

**Comment by zxzxwu** [comment]
Then in short, the answer is NO. Bumble cannot do this.

Your requirement can only be met by replacing the Bluetooth HAL of your Android device with an Bluetooth simulator. You will need an entire Android codebase and many hacks to achieve that. It's not worthy.
