### ISSUE TITLE
Using bumble to automate test for bluetooth-paring device (with android emulator)

### ISSUE THREAD

**Issue by WenhaoWu** [google/bumble#416]
Hello, I came across this package and wonder if this is suitable for automating test for an android app that integrates with third-party bluetooth device. Basically I want to set-up a local server which broadcast a sequential of byte signals, and the app running in android emulator can receive these signals through bluetooth and act accordingly. 

I follow the [android example](https://google.github.io/bumble/platforms/android.html) which runs the gatt_client with android netsim, but I don't see any paring device from the android emulator. However it does print the bluetooth address of the android emulator in console, so I guess the connection is successful?  BTW I am running the whole stack in a MacBook so there is physical bluetooth support, not sure if it matters.

![Screenshot 2024-01-31 at 10 59 34](https://github.com/google/bumble/assets/7606791/dac59360-4a4d-40f0-b250-441d85864e8c)

Moreover is there a direct example for sending and reading bluetooth signals from android emulator? I can't open the [api page](https://google.github.io/bumble/api/guide.html) for some reason.

Thanks in advance for any support :)

**Comment by WenhaoWu** [comment]
Thanks @zxzxwu, now with run_csis_servers.py I can see the pairing device in android emulator. But actually quite redundant to pair the device every time we need to run the test. Is it so with GATT we can send bluetooth data packets directly without paring first?

**Comment by zxzxwu** [comment]
Using GATT doesn't require pairing. You can use GATT and BLE API to establish a connection. 
See: https://developer.android.com/develop/connectivity/bluetooth/ble/transfer-ble-data?hl=en
