### ISSUE TITLE
How to add ‎manufacturer_specific_data‎ in device advertising data?

### ISSUE THREAD

**Issue by WenhaoWu** [google/bumble#421]
Hello, following this [android example](https://google.github.io/bumble/platforms/android.html) I am now able to connect the local gatt_server to android emulator. However in my app's implementation I need to verify the manufacturer_specific_data‎ before transferring data package. Looking at the [device.py](https://github.com/google/bumble/blob/d15bc7d6641552d5e90e611e0ba7eb15b02efe7a/bumble/device.py#L958-L1017) I don't see a way to add manufacturer_specific_data‎ for advertising. Can I do it with the device info service such as in this [example](https://github.com/google/bumble/blob/main/examples/run_gatt_server.py#L91-L106)?

![Screenshot 2024-02-02 at 9 14 53](https://github.com/google/bumble/assets/7606791/8d0d5ba0-e815-4a1e-8170-5f50ebf4d563)

**Comment by barbibulle** [comment]
In your app, you can set the device's advertising data by calling `device.advertising_data = ...`.
You can construct this byte array by serializing an instance of the `AdvertisingData` class, which you construct by passing an array of (<advertising-type-id>, <advertising-data-bytes>) tuples.
Look for a few examples under examples/ where the advertising data is set.
For manufacturer-specific data, the type ID is `AdvertisingData.MANUFACTURER_SPECIFIC_DATA`.
So, for example, if you want to include in your advertising data a local name as well as manufacturer-specific data, you would have something like:
```
 device.advertising_data = bytes(
        AdvertisingData(
            [
                (
                    AdvertisingData.COMPLETE_LOCAL_NAME,
                    bytes('MyDevice', 'utf-8'),
                ),
                (
                    AdvertisingData.MANUFACTURER_SPECIFIC_DATA,
                    my_manufacturer_data_bytes,
                )
            ]
        )
    )
```
(of course, you may want other elements in there too, depending on what your requirements are, just pay attention to the fact that the advertising data is limited in size. One common technique to allow more data in advertisements (like longer devices names) is to put some of the data in the advertising data and some in the scan response)

**Comment by virodoran** [comment]
> One common technique to allow more data in advertisements (like longer devices names) is to put some of the data in the advertising data and some in the scan response)

If anyone else runs into this and wants an example, my solution looked like this. I still ran into a size issue in the scan response data though, and had to make the device name very small (1 byte) to compensate. Not sure if there's a better solution for that.

```
# Set the advertising data
device.advertising_data = bytes(
    AdvertisingData(
        [
            (
                AdvertisingData.COMPLETE_LIST_OF_128_BIT_SERVICE_CLASS_UUIDS,
                bytes(SERVICE_UUID),
            )
        ]
    )
)
device.scan_response_data = bytes(
    AdvertisingData(
        [
            (
                AdvertisingData.COMPLETE_LOCAL_NAME,
                bytes('a', 'utf-8'),  # Can't be more than 1 byte or we run out of room?
            ),
            (
                AdvertisingData.MANUFACTURER_SPECIFIC_DATA,
                binascii.unhexlify('2e00deadbeef1337')
            ),
        ]
    )
)
return device, characteristic
```
