### ISSUE TITLE
Bumble windows install keeps failing.

### ISSUE THREAD

**Issue by rsrikaan** [google/bumble#432]
pip install bumble keeps failing for me as the its not able to build the wheel. Has anybody faced this? how do I fix this. 
![image](https://github.com/google/bumble/assets/148060960/bbdcee8b-a095-4d16-a8a9-37c2153a0992)

**Comment by barbibulle** [comment]
I just tested a fresh install on a Windows 10 machine, that worked Ok.
What version of Windows are you using? It seems that the ``grpcio` package is the one that's failing to install. 
Could you try installing `grpcio` with `pip` directly, so see if maybe a different version of the package works on your system (the current version referenced by the `bumble` build is `1.57.0` but if newer versions fix compatibility issues with Windows, we can easily update the reference)

**Comment by rsrikaan** [comment]
HI, I think its a python version issue, i had python 3.12, tried by changing it to 3.11, it worked
