### ISSUE TITLE
Hangs at HCI_INTEL_DDC_CONFIG_WRITE_COMMAND with CSR Bluetooth dongle

### ISSUE THREAD

**Issue by ftab** [google/bumble#444]
I have an Ubuntu 22.04 desktop with a USB Bluetooth dongle from cinolink, with CSR 8510 A10 chipset. I can't get Bumble examples to run on this device, it hangs at HCI_INTEL_DDC_CONFIG_WRITE_COMMAND
```
# python controller_info.py usb:0a12:0001
DEBUG:asyncio:Using selector: EpollSelector
<<< connecting to HCI...
DEBUG:bumble.transport.usb:loading libusb library at /usr/local/lib/python3.10/dist-packages/libusb_package/libusb-1.0.so
DEBUG:bumble.transport.usb:USB Device: Bus 003 Device 052: ID 0a12:0001
DEBUG:bumble.transport.usb:selected endpoints: configuration=1, interface=0, setting=0, acl_in=0x82, acl_out=0x02, events_in=0x81, 
DEBUG:bumble.transport.usb:auto-detaching kernel driver
DEBUG:bumble.transport.usb:current configuration = 1
DEBUG:bumble.transport.usb:starting USB event loop
<<< connected
DEBUG:bumble.drivers:Probing driver class: rtk
DEBUG:bumble.drivers.rtk:USB device (0A12, 0001) not in known list
DEBUG:bumble.drivers:Probing driver class: intel
DEBUG:bumble.drivers:Instantiated intel driver
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_RESET_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 1
  command_opcode:          HCI_RESET_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_INTEL_DDC_CONFIG_WRITE_COMMAND:
  params: [3, 228, 2, 0]
```
Just gets stuck there

Any ideas? I don't know enough about bumble to know if i can just bypass this command somehow. Just got started today.

I was able to run it on a ThinkPad with an Intel Wireless Bluetooth chip (usb:8087:0029) but that isn't my main Linux machine.

**Comment by barbibulle** [comment]
The intel command should not be sent when the Intel driver isn’t explicitly requested. It looks like a recent merge broke that. I’ll look at pushing a fix asap.

**Comment by ftab** [comment]
Looks like that works. I checked it out and I'm able to run bumble on my main box with the CSR dongle now. Thanks for the quick fix!
