### ISSUE TITLE
grpcio 1.57.0 fails to build with Python 3.12 on aarch64 MacOS with Apple Silicon

### ISSUE THREAD

**Issue by zakx** [google/bumble#459]
See https://github.com/grpc/grpc/pull/34398

Binary wheels supporting Python 3.12 are available for MacOS aarch64 for grpcio versions 1.62.1 and greater. Can you bump the required version for grpcio and grpcio-tools?

**Comment by barbibulle** [comment]
This will be fixed by https://github.com/google/bumble/pull/456 (waiting for some upstream project updates before we can merge the PR)
