### ISSUE TITLE
Using Bumble with Protobuf < 3.20

### ISSUE THREAD

**Issue by hkpeprah** [google/bumble#471]
## Summary

`bumble` has a requirement on `protobuf >= 3.12.4`, but `bt-test-interfaces` has a requirement on `protobuf>=4.22.0`. When attempting to install `bumble` in an environment where `protobuf~=3`, we run into conflict issues with `pip` due to our packages using `protobuf 3.20`, while `bt-test-interfaces` is requesting `protobuf 4.22.0`. Based on what I can see, `bt-test-interfaces` exports `pandora` for Bluetooth testing, and unless you're using the `bumble.pandora` sub-package, you don't need `pandora`: https://github.com/search?q=repo%3Agoogle%2Fbumble+pandora&type=code.

## Example

```
Could not find a version that matches protobuf<=3.20,>=3.12.4,>=4.22.0
There are incompatible versions in the resolved dependencies:
  protobuf>=3.12.4 (from bumble==0.0.190->-r requirements.in.tmp (line 43))
  protobuf>=4.22.0 (from bt-test-interfaces==0.0.6->-r requirements.in.tmp (line 44))
  protobuf<=3.20 (from internal-package==7.1.0->-r requirements.in.tmp (line 21))
```

## Request

Would it be possible to have `bt-test-interfaces` as an `extra-requires`? So that something like `pip install bumble[pandora]` would install `bt-test-interfaces` for those who use `pandora`?

**Comment by barbibulle** [comment]
This should be fixed now with #472

**Comment by hkpeprah** [comment]
Hey @barbibulle , thanks for the quick turn-around. I looked at the patch, and it seems to have bumped the `protobuf` requirement on `bumble` itself from `3.14 -> 4.X`, which still leads to this failure. Is `protobuf` `4.X` requirement for using `bumble`, or just for using `pandora`? My hope was that the `bumble` requirement itself being `>= 3.12.4` would be left alone.

**Comment by barbibulle** [comment]
I've pushed a new PR that reverts the min version to 3.x. I hope this works.
