### ISSUE TITLE
BLE: Unable to request pairing / Unable to reconnect

### ISSUE THREAD

**Issue by cbout22** [google/bumble#498]
Hi,

Host : WSL2 + USB ASUS-BT500 + Python 3.10.14
Bumble Version : 0.0.192

While using examples and `pair.py` I face two issues that I didn't face before upgrading bumble.

1. Unable to reconnect to bumble's examples after performing a disconnect
2. BLE client does not receive pairing request from BLE server and unable to reconnect after performing a disconnect.

Since yesterday, I used Bumble 0.0.172 to test my android app, I tried the new version of Bumble, but it doesn't work any more.

## Unable to reconnect :

Using `examples/battery_server.py` I can perform a connexion using NRF connect. Once I disconnect, LE **doesn't restart** and I was **unable to reconnect**.

Command Line : 
`python3 examples/battery_server.py ./examples/device1.json usb:0`

Logging : 
```
DEBUG:asyncio:Using selector: EpollSelector
DEBUG:bumble.transport.usb:loading libusb library at /home/cbout/.pyenv/versions/3.10.14/lib/python3.10/site-packages/libusb_package/libusb-1.0.so
DEBUG:bumble.transport.usb:USB Device: Bus 001 Device 002: ID 0b05:190e
DEBUG:bumble.transport.usb:selected endpoints: configuration=1, interface=0, setting=0, acl_in=0x82, acl_out=0x02, events_in=0x81, 
DEBUG:bumble.transport.usb:auto-detaching kernel driver
DEBUG:bumble.transport.usb:current configuration = 1
DEBUG:bumble.transport.usb:starting USB event loop
DEBUG:bumble.drivers:Probing driver class: rtk
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_RESET_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 3
  command_opcode:          HCI_RESET_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 2
  command_opcode:          HCI_READ_LOCAL_VERSION_INFORMATION_COMMAND
  return_parameters:       
    status:             HCI_SUCCESS
    hci_version:        10
    hci_subversion:     11
    lmp_version:        10
    company_identifier: 93
    lmp_subversion:     34657
DEBUG:bumble.drivers.rtk:looking for a driver: 0x8761 (0x0A, 0x000B)
WARNING:bumble.drivers.rtk:Firmware file rtl8761bu_fw.bin not found
WARNING:bumble.drivers.rtk:See https://google.github.io/bumble/drivers/realtek.html
DEBUG:bumble.drivers:Probing driver class: intel
DEBUG:bumble.drivers.intel:USB device (0B05, 190E) not in known list
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_RESET_COMMAND
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_COMMAND_COMPLETE_EVENT:
  num_hci_command_packets: 3
  command_opcode:          HCI_RESET_COMMAND
  return_parameters:       HCI_SUCCESS
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_READ_LOCAL_SUPPORTED_COMMANDS_COMMAND
... 
<SOME DEBUG>
...
DEBUG:bumble.host:### CONTROLLER -> HOST: ACL: handle=0x0018, pb=2, bc=0, data_total_length=9, data=050004000409000900
DEBUG:bumble.hci:<<< ACL PDU: 050004000409000900
DEBUG:bumble.gatt_server:GATT Request to server: [0x0018] ATT_FIND_INFORMATION_REQUEST:
  starting_handle: 0x0009
  ending_handle:   0x0009
DEBUG:bumble.gatt_server:GATT Response from server: [0x0018] ATT_FIND_INFORMATION_RESPONSE:
  format:      1
  information: 0x0009:0229
DEBUG:bumble.host:>>> ACL packet enqueue: (CID=4) ACL: handle=0x0018, pb=0, bc=0, data_total_length=10, data=06000400050109000229
DEBUG:bumble.host:### HOST -> CONTROLLER: ACL: handle=0x0018, pb=0, bc=0, data_total_length=10, data=06000400050109000229
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:        1
  connection_handle[0]:     24
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_NUMBER_OF_COMPLETED_PACKETS_EVENT:
  number_of_handles:        1
  connection_handle[0]:     24
  num_completed_packets[0]: 1
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_LE_CONNECTION_UPDATE_COMPLETE_EVENT:
  status:              HCI_SUCCESS
  connection_handle:   24
  connection_interval: 36
  peripheral_latency:  0
  supervision_timeout: 500
DEBUG:bumble.device:*** Connection Parameters Update: [0x0018] E8:78:29:C1:64:EB/P as PERIPHERAL, ConnectionParameters(connection_interval=36, peripheral_latency=0, supervision_timeout=500
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_DISCONNECTION_COMPLETE_EVENT:
  status:            HCI_SUCCESS
  connection_handle: 24
  reason:            HCI_REMOTE_USER_TERMINATED_CONNECTION_ERROR
DEBUG:bumble.host:### DISCONNECTION: [0x0018] 48:AC:27:DE:40:87 reason=19
DEBUG:bumble.device:*** Disconnection: [0x0018] E8:78:29:C1:64:EB/P as PERIPHERAL, reason=19
DEBUG:bumble.l2cap:disconnection from 24, cleaning up channels
```

## Unable to pair

Using `pair.py` with request parameters, I've got the following error :
```
WARNING:bumble.device:no connection for handle 0x0018
```
LE connexion is performed and I can read characteristics. Although, I can't reconnect once I disconnect my smartphone.
My smartphone **doesn't receive** pairing request.

Command Line : 
`python3 apps/pair.py --request ./examples/device1.json usb:0`

Logging :

```
DEBUG:asyncio:Using selector: EpollSelector
<<< connecting to HCI...
DEBUG:bumble.transport.usb:loading libusb library at /home/cbout/.pyenv/versions/3.10.14/lib/python3.10/site-packages/libusb_package/libusb-1.0.so
DEBUG:bumble.transport.usb:USB Device: Bus 001 Device 002: ID 0b05:190e
DEBUG:bumble.transport.usb:selected endpoints: configuration=1, interface=0, setting=0, acl_in=0x82, acl_out=0x02, events_in=0x81, 
DEBUG:bumble.transport.usb:auto-detaching kernel driver
DEBUG:bumble.transport.usb:current configuration = 1
DEBUG:bumble.transport.usb:starting USB event loop
<<< connected
DEBUG:bumble.drivers:Probing driver class: rtk
DEBUG:bumble.host:### HOST -> CONTROLLER: HCI_RESET_COMMAND
DEBUG:bumble.host:reset not done, ignoring packet from controller
...
<SOME DEBUG>
...
DEBUG:bumble.drivers.rtk:looking for a driver: 0x8761 (0x0A, 0x000B)
WARNING:bumble.drivers.rtk:Firmware file rtl8761bu_fw.bin not found
WARNING:bumble.drivers.rtk:See https://google.github.io/bumble/drivers/realtek.html
DEBUG:bumble.drivers:Probing driver class: intel
DEBUG:bumble.drivers.intel:USB device (0B05, 190E) not in known list
...
<SOME DEBUG>
...
DEBUG:bumble.device:*** Connection Parameters Update: [0x0018] E8:78:29:C1:64:EB/P as PERIPHERAL, ConnectionParameters(connection_interval=36, peripheral_latency=0, supervision_timeout=500
DEBUG:bumble.host:### CONTROLLER -> HOST: HCI_DISCONNECTION_COMPLETE_EVENT:
  status:            HCI_SUCCESS
  connection_handle: 24
  reason:            HCI_REMOTE_USER_TERMINATED_CONNECTION_ERROR
DEBUG:bumble.host:### DISCONNECTION: [0x0018] 7E:BC:69:8D:06:64 reason=19
DEBUG:bumble.device:*** Disconnection: [0x0018] E8:78:29:C1:64:EB/P as PERIPHERAL, reason=19
DEBUG:bumble.l2cap:disconnection from 24, cleaning up channels
```

**Comment by barbibulle** [comment]
Hi.
Regarding the first issue (reconnection): indeed, this is a regression bug. Something broke a while back with the advertising auto-restart support and went undetected. PR #500 should fix that.
Regarding the second issue: I'm not able to reproduce the issue.
I have tested this quick scenario with an iPhone:
1/ python3 apps/pair.py --request ./examples/device1.json usb:0
A popup shows up on the phone asking me if I want to pair. I tap yes. On the command line, I'm asked to verify the PIN code
(In your test, did you respond to the CLI PIN code verification question? If not, then the pairing won't complete)

```
❯ python apps/pair.py --request ./examples/device1.json usb:0
<<< connecting to HCI...
<<< connected
<<< Connection: Connection(handle=0x0040, role=PERIPHERAL, self_address=F0:F1:F2:F3:F4:F5, peer_address=52:89:FA:7F:F3:56)
>>> Requesting pairing
***-----------------------------------
*** Pairing starting
***-----------------------------------
###-----------------------------------
### Pairing with iPhone [52:89:FA:7F:F3:56]
###-----------------------------------
>>> Does the other device display 036492? yes
@@@-----------------------------------
@@@ Connection is encrypted
@@@-----------------------------------
***-----------------------------------
*** Paired! (peer identity=EC:81:50:43:5A:EE/P)
*** address_type: 0
*** ltk:
***   value: 77e383254a280d25a69c4d581b23e190
***   authenticated: True
*** irk:
***   value: 0e93119440c4f668109cf89f9e88d079
***   authenticated: True
***-----------------------------------
```
After that, I can see 'Bumble' in my list of paired devices.

I have also tested with an Android phone. It works, too, but is a bit more complicated: when the phone connects, you get a first notification, asking you if you want to pair. You need to tap "yes". Then, you see a second notification, asking you (again) if you want to pair. You need to tap "yes" again, and then you see a popup asking you to confirm the PIN code. You need to tap and confirm.
It is somewhat convoluted, but that's the way Android currently implements pairing/bonding when initiated by a peripheral request.

Which type of phone are you using in your tests? What type of notification/popup do you see?

**Comment by cbout22** [comment]
Hi,

Thanks for your reactivity and the quality of your work!

## Incapacity to pair :

I **didn't receive any pop-up** on my two smartphones. The observed behaviour is the following :
1. Try to connect with nrf connect
2. A Warning is displayed (same for every smartphone) : `WARNING:bumble.device:no connection for handle 0x0018`
3.a Nothing happen in the python app (see output below)
3.b Smartphone is connected and can access to ble service and characteristics.

I take care to verify that the device is not known or stored as bonded/paired in the smartphone.

Smartphones : 
- Fairphone 4 - Android 13
- Google Pixel 7 - Android 14

Computer setup : WSL2 with Ubuntu 22.04, Dongle Asus BT500, python 3.10.14

Command lines :
```bash
$ cd path/to/bumble
$ python apps/pair.py --request ./examples/device1.json usb:0
```

Cli outputs : 
> Note : `bumble.drivers.rtk` 's warning was present in 0.0.172 too and pairing worked at this moment
```bash
<<< connecting to HCI...
<<< connected
WARNING:bumble.drivers.rtk:Firmware file rtl8761bu_fw.bin not found
WARNING:bumble.drivers.rtk:See https://google.github.io/bumble/drivers/realtek.html
WARNING:bumble.device:no connection for handle 0x0018
```

Smartphone Sides : (debug log from NRF connect)
```
nRF Connect, 2024-06-04
Bumble (F0:F1:F2:F3:F4:F5)
I	09:43:03.896	[Server] Server started
V	09:43:03.900	Heart Rate (0x180D)
- Heart Rate Measurement [N] (0x2A37)
   Client Characteristic Configuration (0x2902)
- Body Sensor Location [R] (0x2A38)
- Heart Rate Control Point [W] (0x2A39)
Unknown Service (0000aaa0-0000-1000-8000-aabbccddeeff)
- Unknown Characteristic [N R] (0000aaa1-0000-1000-8000-aabbccddeeff)
   Client Characteristic Configuration (0x2902)
   Unknown Descriptor (0000aab0-0000-1000-8000-aabbccddeeff)
   Characteristic User Description (0x2901)
   Characteristic Presentation Format (0x2904)
- Unknown Characteristic [I W WNR] (0000aaa2-0000-1000-8000-aabbccddeeff)
   Client Characteristic Configuration (0x2902)
User Data (0x181C)
- First Name [R W] (0x2A8A)
- Last Name [R W] (0x2A90)
- Gender [R W] (0x2A8C)
V	09:43:04.174	Connecting to F0:F1:F2:F3:F4:F5...
D	09:43:04.174	gatt = device.connectGatt(autoConnect = false, TRANSPORT_LE, preferred PHY = LE 1M)
D	09:43:09.157	[Server callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	09:43:09.157	[Server] Device with address F0:F1:F2:F3:F4:F5 connected
D	09:43:09.166	[Callback] Connection state changed with status: 0 and new state: CONNECTED (2)
I	09:43:09.167	Connected to F0:F1:F2:F3:F4:F5
V	09:43:09.226	Discovering services...
D	09:43:09.226	gatt.discoverServices()
D	09:43:09.232	[Broadcast] Action received: android.bluetooth.device.action.ACL_CONNECTED
I	09:43:09.607	Connection parameters updated (interval: 7.5ms, latency: 0, timeout: 5000ms)
D	09:43:09.710	[Callback] Services discovered with status: 0
I	09:43:09.711	Services discovered
V	09:43:09.714	Generic Access (0x1800)
- Device Name [R] (0x2A00)
- Appearance [R] (0x2A01)
Unknown Service (50db505c-8ac4-4738-8448-3b1d9cc09cc5)
- Unknown Characteristic [R W] (552957fb-cf1f-4a31-9535-e78847e1a714)
I	09:43:09.828	Connection parameters updated (interval: 45.0ms, latency: 0, timeout: 5000ms)
D	09:47:18.817	[Callback] Connection state changed with status: 19 and new state: DISCONNECTED (0)
W	09:47:18.817	Connection terminated by peer (status 19)
I	09:47:18.817	Disconnected
D	09:47:18.818	[Server callback] Connection state changed with status: 0 and new state: DISCONNECTED (0)
I	09:47:18.818	[Server] Device disconnected
D	09:47:18.867	[Broadcast] Action received: android.bluetooth.device.action.ACL_DISCONNECTED
```

**Comment by barbibulle** [comment]
I was able to replicate the issue, using the same USB dongle (ASUS BT500). Somehow, the order in which some of the events are emitted by this controller is different from the way other controllers behave, which is why the `no connection for handle 0x0018` appears. I will investigate and fix that.
Regarding the `Ignoring event HCI_LE_CHANNEL_SELECTION_ALGORITHM_EVENT` message, that's not a problem. It's just that that version of the code doesn't handle this event from the controller, but since that's purely informative, it doesn't cause any problem.

**Comment by cbout22** [comment]
Thanks :)

**Comment by cbout22** [comment]
Could you provide us the reference of the dongle you use or any dongle you support for the moment?

**Comment by barbibulle** [comment]
The issue that caused `no connection for handle 0x0018` on this BT dongle is now fixed (somehow, this BT dongle behaves differently from others in the order of events it emits for extended advertising, but it seems to be allowed by the spec, even if it's an odd choice, so the stack now supports it).
For pairing, while you can definitely use the `--request` mode of the pairing app, it isn't necessarily something I'd recommend, as it isn't typical. Usually, you'll have the pairing initiated by the central (like a phone connecting to an. accessory). This can be done via the Bluetooth settings app on Android for example, or via an API. iOS doesn't have an API for that, and pairing from the settings doesn't seem to let you do that for LE only devices, so there's a different mechanism there: when an iOS app tries to access a GATT characteristic that returns an authentication error when not paired, pairing will automatically be initiated. The `pair.py` app includes a GATT server with such a characterisic, so if you access it from the phone, it should trigger pairing.

Also, answering your last question: we've had great results with the Laird BT851 USB dongle, which supports Classic and LE. It is very reliable. However, it doesn't support some of the most recent Bluetooth features, like extended advertising. For LE-only controllers, the nrf52840 USB dongles work great. We've had good results with the Zephyr USB HCI "sample app" running on those. It does require flashing a custom FW on the dongle (I don't know of anyone selling dongles pre-flashed with USB HCI mode).

**Comment by cbout22** [comment]
I greatly appreciate your help!

Unfortunately, I try to develop an app for a vendor product that doesn't match BLE standard very well. I configured the pair.py app to mimic connection of this product.

I'll explore if those references match my needs 👍
