### ISSUE TITLE
Virtual device

### ISSUE THREAD

**Issue by Eonassis** [google/bumble#519]
I need to create a virtual device on a physical Android phone, with version 7, so that the Android connects to it, is it possible to do this with Bumble?

**Comment by Eonassis** [comment]
I asked again because I saw that the bumble project had evolved a lot and I saw the Android Remote HCI app on the extra page, so I thought it could be something new. thanks for answering.

**Comment by zxzxwu** [comment]
If you really want Bumble to help you, the only way is to have a physical Bluetooth controller running Bumble, and let your Android phone connect to it.
