### ISSUE TITLE
Physical usb Reset failure (enumeration) - any work arounds I can try

### ISSUE THREAD

**Issue by mscottwvc** [google/bumble#557]
The root cause might be the device itself and not Bumble, but I am using a physical hub device (m.2. chip Intel AX200) on Ubuntu.  I am largely using the stock bumble scan code.  Sometimes when I start bumble there is an issue with the device and reset fails during power on.  I tried to force a reset prior to power_on() and even retry if the first one fails but the second  one fails as well.  If I relaunch python after the failure that the next iteration works (maybe because bumble releases the device and the OS resets it) is there anything I can try instead of that process?  The error below is just using power_on.

```python
WARNING:bumble.host:HCI_RESET_COMMAND failed (HCI_UNKNOWN_HCI_COMMAND_ERROR)
WARNING:bumble.host:!!! Exception while sending command: HCI_Error(hci/HCI_UNKNOWN_HCI_COMMAND_ERROR [0x1])
Traceback (most recent call last):
  File "/var/opt/hsh/hsh_bsp/scan/build/../bumbleScanRssi.py", line 205, in <module>
    main()
    ~~~~^^
  File "/home/hsh/.local/lib/python3.13/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/hsh/.local/lib/python3.13/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/hsh/.local/lib/python3.13/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hsh/.local/lib/python3.13/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/var/opt/hsh/hsh_bsp/scan/build/../bumbleScanRssi.py", line 201, in main
    asyncio.run(scan(min_rssi, passive, scan_interval, scan_window, phy, filter_duplicates, raw, keystore_file, device_config, transport, mailbox_pos))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/usr/local/lib/python3.13/asyncio/base_events.py", line 721, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/var/opt/hsh/hsh_bsp/scan/build/../bumbleScanRssi.py", line 158, in scan
    await device.power_on()
  File "/home/hsh/.local/pipx/venvs/bumble/lib/python3.11/site-packages/bumble/device.py", line 2193, in power_on
    await self.host.reset()
  File "/home/hsh/.local/pipx/venvs/bumble/lib/python3.11/site-packages/bumble/host.py", line 239, in reset
    await self.send_command(hci.HCI_Reset_Command(), check_result=True)
  File "/home/hsh/.local/pipx/venvs/bumble/lib/python3.11/site-packages/bumble/host.py", line 555, in send_command
    raise error
  File "/home/hsh/.local/pipx/venvs/bumble/lib/python3.11/site-packages/bumble/host.py", line 548, in send_command
    raise hci.HCI_Error(status)
bumble.hci.HCI_Error: HCI_Error(hci/HCI_UNKNOWN_HCI_COMMAND_ERROR [0x1])
```

**Comment by barbibulle** [comment]
A couple things come to mind:
  * 1/ If you're on Linux, and the controller is supported by your Linux kernel+drivers, you may want to go through the kernel rather than directly to the controller (this way you benefit from other things the kernel driver may do for you, like loading FW images). See https://google.github.io/bumble/platforms/linux.html#using-hci-sockets for details.
  * 2/ If the controller is in a bad state, sending an HCI_RESET command might not help much, because that's an actual HCI command, so if there's an issue with sending HCI commands in the first place, that won't actually reset anything. What you need here is likely a lower-level reset. It may be possible to power-cycle the controller. Something like: https://github.com/netinvent/usb_resetter might help.

**Comment by mscottwvc** [comment]
Thanks - I tried hci socket , but get an exception: Bluetooth HCI sockets not supported on this platform.  I'm running ubuntu 23.10, so not sure why its mad.  Hciconfig works and shows the hci device I want to use as Down.

**Comment by barbibulle** [comment]
> Thanks - I tried hci socket , but get an exception: Bluetooth HCI sockets not supported on this platform. I'm running ubuntu 23.10, so not sure why its mad. Hciconfig works and shows the hci device I want to use as Down.

If you see the error "Bluetooth HCI sockets not supported on this platform", it means that the Python runtime on your platform was compiled without support for the `socket.AF_BLUETOOTH` constant. Which Python runtime are you using? (some python environments, like Anaconda, bring their own python runtimes, often not compiled with all the platform support. See https://stackoverflow.com/questions/29107537/missing-socket-af-bluetooth-in-anaconda-python for an example).

**Comment by mscottwvc** [comment]
Thanks for the info! I was using python3.13 (I think I it was a prebuilt one), but the variant didnt have it.  I built a new one from the source and now it works.  Using the socket seems to be much more reliable now so far and faster to release, since the OS doesnt have to reenumerate the device now upon bumble stopping.
