### ISSUE TITLE
Hci Bridge - unpack_from requires a buffer of at least 3 bytes

### ISSUE THREAD

**Issue by Ali-Olayan** [google/bumble#558]
Hi,

### **Objective:**
	Establish connection between external Bluetooth device and the emulator.

### **Issue:**
	After launching emulator from CMD I get the following error in running instance of hci_bridge CMD:
	struct.error: unpack_from requires a buffer of at least 3 bytes for unpacking 2 bytes at offset 1 (actual buffer size is 2) 
	
### **Stacktrace:**
		ERROR:bumble.transport.usb:←[31m!!! Exception in sink.on_packet: unpack_from requires a buffer of at least 3 bytes for unpacking 2 bytes at offset 1 (actual buffer size is 2)←[0m
	Traceback (most recent call last):
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\transport\usb.py", line 290, in dequeue
		self.sink.on_packet(packet)
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\bridge.py", line 40, in on_packet
		hci_packet = HCI_Packet.from_bytes(packet)
					 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\hci.py", line 2037, in from_bytes
		return HCI_Event.from_bytes(packet)
			   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\hci.py", line 4859, in from_bytes
		return cls.from_parameters(parameters)  # type: ignore
			   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\hci.py", line 5869, in from_parameters
		return_parameters = cls.parse_return_parameters(self.return_parameters)
							^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\hci.py", line 2154, in parse_return_parameters
		return_parameters = HCI_Object.from_bytes(
							^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\hci.py", line 1679, in from_bytes
		return cls(fields, **cls.dict_from_bytes(data, offset, fields))
							 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\hci.py", line 1578, in dict_from_bytes
		field_value, field_size = HCI_Object.parse_field(data, offset, field_type)
								  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	  File "C:\Users\xx\AppData\Roaming\Python\Python312\site-packages\bumble\hci.py", line 1534, in parse_field
		return (struct.unpack_from('<H', data, offset)[0], 2)
				^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
	struct.error: unpack_from requires a buffer of at least 3 bytes for unpacking 2 bytes at offset 1 (actual buffer size is 2)
	
	
### **Software and Hardware:**
	Windows 10
	Pixel 8 API 35
	Android Studio Koala | 2024.1.2
	Bumble 0.0.198
	Generic Unbranded Bluetooth USB Dongle advertised as 5.0 (Showing as USB CSR8510 A10)
                ←[30;43mID 0A12:0001←[0m
                ←[34m  Bumble Transport Names:←[0m ←[36musb:1←[0m or ←[36musb:0A12:0001←[0m
                ←[32m  Bus/Device:            ←[0m 001/014
                ←[32m  Class:                 ←[0m Wireless Controller
                ←[32m  Subclass/Protocol:     ←[0m 1/1 [Bluetooth]
                ←[32m  Product:               ←[0m CSR8510 A10
                  Configuration 1
                      Interface: 0 (Wireless Controller, 1/1 [Bluetooth])
                        Endpoint 0x83: INTERRUPT IN
                        Endpoint 0x01: BULK OUT
                        Endpoint 0x81: BULK IN
                      Interface: 1/0 (Wireless Controller, 1/1 [Bluetooth])
                        Endpoint 0x02: ISOCHRONOUS OUT
                        Endpoint 0x82: ISOCHRONOUS IN
                      Interface: 1/1 (Wireless Controller, 1/1 [Bluetooth])
                        Endpoint 0x02: ISOCHRONOUS OUT
                        Endpoint 0x82: ISOCHRONOUS IN
                      Interface: 1/2 (Wireless Controller, 1/1 [Bluetooth])
                        Endpoint 0x02: ISOCHRONOUS OUT
                        Endpoint 0x82: ISOCHRONOUS IN
                      Interface: 1/3 (Wireless Controller, 1/1 [Bluetooth])
                        Endpoint 0x02: ISOCHRONOUS OUT
                        Endpoint 0x82: ISOCHRONOUS IN
                      Interface: 1/4 (Wireless Controller, 1/1 [Bluetooth])
                        Endpoint 0x02: ISOCHRONOUS OUT
                        Endpoint 0x82: ISOCHRONOUS IN
                      Interface: 1/5 (Wireless Controller, 1/1 [Bluetooth])
                        Endpoint 0x02: ISOCHRONOUS OUT
                        Endpoint 0x82: ISOCHRONOUS IN
	

### **Steps to reproduce:**
		
	Command 01:
		python apps/hci_bridge.py android-netsim:_:8877,mode=controller usb:1
		
	Result:		
		>>> connecting to HCI...
		>>> connected
		>>> connecting to HCI...
		>>> connected
	
	Command 02:
		emulator -packet-streamer-endpoint localhost:8877 -avd Pixel_8_API_35
		
	Result (the emulator will launch however in hci_bridge instance I will get the following):
		struct.error: unpack_from requires a buffer of at least 3 bytes for unpacking 2 bytes at offset 1 (actual buffer size is 2)
						
### Notes:
	Within the emulator the Bluetooth will remain off even if I try to toggle it on.

**Comment by Ali-Olayan** [comment]
Issue is completely resolved by using Bumble compatible USB Bluetooth dongle.

**Comment by acieszkiel** [comment]
Hello, I'd like to ask which USB Bluetooth dongles are compatible with Bumble?

Thank you in advance.

Looking forward to hearing from you.
