### ISSUE TITLE
Android + hci-bridge + hic-socket issues

### ISSUE THREAD

**Issue by mscottwvc** [google/bumble#575]
Maybe my understanding is flawed?  Here is my thought process:

To use bumble to pass in a physical bt controller to an android emulator, example: usb:0, then the android emulator must have the drivers for that bt controller.

If an hci-socket is passed in, example: hci-socket:0, then the android device does not need to have drivers for that controller.

I am trying to pass in a nordic hci_usb device through linux.  Bumble seems to interact with the hci-socket fine on linux ( I can do scans without issue, etc), but when I try to bridge it to an emulator the emulator doesnt take it.   What did I miss?

**Comment by zxzxwu** [comment]
With HCI Bridge, Android doesn't need to drive HCI transports directly. Acutally, Android itself can only interacts with TCP socket, and it relies on netsim and HCI bridge to bridge between TCP socket and raw transports.

Still, I am not sure why HCI socket is involved here since you are using USB dongle. Ideally you only need to run HCI bridge first, and then launch emulator with specific parameters. https://google.github.io/bumble/platforms/android.html#connecting-a-custom-virtual-controller

Can you share what's your command (and steps) to launch HCI bridge and Android Emulators?

**Comment by mscottwvc** [comment]
So are you saying either transport should work?

Running latest emulator 35.2.10
Tried a few emulators but last I tried was Pixel 2 shell with Android 13 x86_64 (google Play)
Bumble log attached
Step 1 :
`BUMBLE_LOGLEVEL=debug bumble-hci-bridge android-netsim:_:8877,mode=controller hci-socket:0`
Step 2:
`emulator -avd zz -port 5554 -no-snapshot-load -packet-streamer-endpoint localhost:8877`

[log.txt](https://github.com/user-attachments/files/17466358/log.txt)

**Comment by barbibulle** [comment]
This should work. 
Note that you might not need to go through `hci-socket` unless you need to go through the Linux kernel to initialize the controller (for example, loading a FW image). If you have a "standard" controller that can be used directly, attached via USB or a serial port, you can use the `usb` transport or the `serial` transport. But there's nothing wrong with going through `hci-socket` if that works.
From the logs here, we can see that the Android BT stack is sending commands that the controller does not understand (ex: `HCI_READ_LOCAL_NAME_COMMAND`, `HCI_WRITE_LE_HOST_SUPPORT_COMMAND`). Normally, the stack will check if a command is supported by the controller before using that, but it may be that the use of some commands is hard-coded and not soft-checked. In particular here, you mention that your controller is a Nordic controller, so BLE only, which may not necessarily be supported by Android (I haven't checked, so I could be wrong).

**Comment by mscottwvc** [comment]
Thanks for the explanation, I tried to short circuit those two just for fun, but didnt seem to help.  I forgot this was a ble only controller so that may be the issue.  Guessing rebuilding android to use ble only probably wouldnt be easy....

Do you know of any bluetooth usb devices that would be similar to the nordic in that it doesnt require firmware to be loaded each time and isn't serial?

**Comment by zxzxwu** [comment]
There are many Bluetooth dongles supporting dual mode (BR/EDR + LE) on Linux, but their compatibility with Android is not sure. Bluetooth USB dongles usually have a very limited capability.

https://a.co/d/1UNYQtV
https://mfactors.com/m88a25-bt-sig-pts-external-usb-bluetooth-adapter-with-intel-be200-card/

**Comment by barbibulle** [comment]
The BT Controller I use the most is the Laird BT851. It supports Classic and LE, as a USB dongle, and does not require any firmware loading. The Realtek-based USB dongles work well as well (they need FW loading, but that's supported by the Bumble library, you can download the FW images and Bumble will use them, see: https://google.github.io/bumble/drivers/realtek.html).
